### PR TITLE
Fixed an issue where calling `prefillInformation` on `NumberInputTextField` would set a wrong text color

### LINKED ISSUE #80: NumberInputTextField text color not working with prefillInformation
I'm having problems setting textColor to `NumberInputTextField` when using with `prefillInformation` with Card.IO integration. I used very hacky workaround for this:

`cardNumberInput.textField(cardNumberInput, shouldChangeCharactersInRange: NSMakeRange(0, cardNumberInput.text!.characters.count), replacementString: cardNumberInput.text!)` 

I guess there is a bigger issue behind this caused by the use of `_textColor` because this seemed to be to only way to trigger `super.textColor` change.

### PR DESCRIPTION
**Pull request by DannyVancura**
These changes treat pre-filling a card number like manually entering one, therefor correctly adjusting text color and notifying a `NumberInputTextField`'s delegate about text changes.

Fixes #80

### CODE REVIEW

File: Pod/Classes/UI/NumberInputTextField.swift [hunk 1]
```diff
@@ -171,9 +171,10 @@ public class NumberInputTextField: StylizedTextField {
         let numberPartiallyValid = type.checkCardNumberPartiallyValid(cardNumber) == .Valid
         
         if numberPartiallyValid {
-            let formatter = cardNumberFormatter
-            text = formatter.formattedCardNumber(unformattedCardNumber)
-            numberInputTextFieldDelegate?.numberInputTextFieldDidChangeText(self)
```
Comment (ThibaultKlein) [inline Pod/Classes/UI/NumberInputTextField.swift]: I assume that calling this delegate was causing the issue. Are there any side effects by not calling it anymore?

Comment (DannyVancura) [inline Pod/Classes/UI/NumberInputTextField.swift]: This method is still called in `textField(self, shouldChangeCharactersInRange: _, replacementString: _)`:

```swift
        if !newValidation.contains(.NumberTooLong) {
            cardNumberFormatter.replaceRangeFormatted(range, inTextField: textField, withString: string)
            numberInputTextFieldDelegate?.numberInputTextFieldDidChangeText(self)
        } else if oldValidation == .Valid {
            // If the card number is already valid, should call numberInputTextFieldDidComplete on delegate
            // then set the text color back to normal and return
            numberInputTextFieldDelegate?.numberInputTextFieldDidComplete(self)
            super.textColor = _textColor
            return false
        } else {
            notifyNumberInvalidity()
        }
```

Instead of replacing the text though, the behavior is to imitate manual user input, which triggers all checks and behaviors (like adjusting the text color in the related issue) related to that.
